pipeline:
  build:
    image: ruby:2.2.1
    commands:
    - bundle install
    - bundle exec rake db:setup
    - bundle exec rake test
    environment:
      - RACK_ENV=test
      - DATABASE_URL=postgres://postgres:postgres@database/myapp_test

services:
  database:
    image: postgres
